name: Publish Release

on:
  release:
    types: [published]

jobs:
  # https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/
  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: pip
    - run: |
        pip install --upgrade pip
        pip install build
    - run: python -m build

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
